CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: [0]
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 10

DATASET:
  DATASET: face
  ROOT: ../data/
  TEST_SET: 'val.txt'
  TRAIN_SET: 'train.txt'
  NUM_CLASSES: 2
MODEL:
  NAME: pp_liteseg
  NUM_OUTPUTS: 3
  PRETRAINED: ""
  TRAIN: False
  ALIGN_CORNERS: false
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [1, 1, 1]
TRAIN:
  IMAGE_SIZE:  # H W
  - 512
  - 512
  BATCH_SIZE_PER_GPU: 8
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 1000
  RANDOM_BRIGHTNESS: true
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.0005
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  DOWNSAMPLERATE: 1
  IGNORE_LABEL: 255
  SCALE_FACTOR: 15
  RANDOM_ROTATE: true
  CONTRAST: true
  SATURATION: true
  HUE: true
TEST:
  IMAGE_SIZE: # H W
  - 512
  - 512
  BATCH_SIZE_PER_GPU: 8
  FLIP_TEST: false
  MULTI_SCALE: false
  SCALE_LIST: [1]
  #0.5,0.75,1.0,1.25,1.5,1.75
  MODEL_FILE: "/root/DDRNet.Pytorch/pretrained_models/checkpoint.pth"
  OUTPUT_INDEX: 0
